### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dtchuink** [ldv-klever/klever#1]
Hi

I would like to try Klever, but cannot find any documentation in that direction. 

Is it possible for you to provide a basic example on how to use it, even with the [sv-benchmarks](https://github.com/sosy-lab/sv-benchmarks) uploaded online?

Thanks

**Comment by eunovm** [comment]
Hi,

Sorry for the delay, we were completely busy last time. I opened the corresponding issue https://forge.ispras.ru/issues/9897, since we use Redmine for development and here is just the mirror.

**Comment by eunovm** [comment]
There is an important update: https://forge.ispras.ru/issues/9897#note-19.
